markdown: kramdown
pygments: true
permalink: /:title.html
kramdown:
  coderay_css: class
exclude: [_public]

default_theme: ribbon
default_lang: en
default_body_class: list

author:
    name: clkao
    company:
        name: 'angularjstw#3'

fork_url: https://github.com/audreyt/moedict-webkit
progress: true
