auto: true
safe: true
server: true
markdown: kramdown
pygments: true
permalink: /:title.html
kramdown:
  coderay_css: class
exclude: [_site]

default_theme: g0v
default_lang: en
default_body_class: list

author:
    name: Audrey Tang
    company:
        name: COSCUP 2013

fork_url: https://github.com/audreyt/moedict-webkit
progress: true
